[theme]
base="dark"
primaryColor="#dc7670"
backgroundColor="#1f1f22"
secondaryBackgroundColor="#2d2d32"
textColor="#eeecec"
font="serif"
redColor="#ffc16e"
orangeColor = "#cb4641"
yellowColor = "#ebc34c"
greenColor = "#77c688"